// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddressAutocompleteController from "./address_autocomplete_controller"
application.register("address-autocomplete", AddressAutocompleteController)

import BooktempController from "./booktemp_controller"
application.register("booktemp", BooktempController)

import ChatroomSubscriptionController from "./chatroom_subscription_controller"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import CheckboxController from "./checkbox_controller"
application.register("checkbox", CheckboxController)

import MapController from "./map_controller"
application.register("map", MapController)

import StartChatController from "./start_chat_controller"
application.register("start-chat", StartChatController)
