meta_product_name: "Binder"
meta_title: "Binder | Goodreads for Modern People"
meta_description: "Finding local community through books"
meta_image: "cover.png" # should exist in `app/assets/images/`
